# Generated by Django 3.2.9 on 2021-11-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Momsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'momsset',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('new', models.BooleanField(default=False)),
                ('best', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(db_constraint='category_id', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Momsset_Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('momsset_id', models.ForeignKey(db_constraint='momsset_id', on_delete=django.db.models.deletion.CASCADE, to='products.momsset')),
                ('products_id', models.ForeignKey(db_constraint='products_id', on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'momsset_Products',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='menu_id',
            field=models.ForeignKey(db_constraint='menu_id', on_delete=django.db.models.deletion.CASCADE, to='products.menu'),
        ),
        migrations.CreateModel(
            name='Allergy_products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy_id', models.ForeignKey(db_constraint='allergy_id', on_delete=django.db.models.deletion.CASCADE, to='products.allergy')),
                ('products_id', models.ForeignKey(db_constraint='products_id', on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'allergy_products',
            },
        ),
    ]
